version: "3.7"
services:
  traggo:
    image: traggo/server:${SOFTWARE_VERSION_TAG}
    restart: always
    ports:
      - 172.17.0.1:3030:3030
    environment:
      TRAGGO_DEFAULT_USER_NAME: ${TRAGGO_DEFAULT_USER_NAME}
      TRAGGO_DEFAULT_USER_PASS: ${ADMIN_PASSWORD}
    volumes:
      - ./traggodata:/opt/traggo/data
